version: "3.1"

services:
  dnsmasq:
    image: ghcr.io/lyekumchew/dnsmasq:latest
    restart: always
    ports:
      - "5380:8080"
      - "53:53"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    environment:
      - HTTP_USER=foo
      - HTTP_PASS=ba
